### ISSUE TITLE
[FEATURE]: Automatic Item Pickup

### ISSUE THREAD

**Issue by TheButterbrotMan** [TBM-Studios/MC-Kingdoms#5]
### Prerequisites

- [X] I am using the latest version of the modpack
- [X] I have checked that this feature request hasn't been suggested before

### Feature Description

I would like to see an automatic item pickup feature added to the modpack. Currently, items need to be manually picked up, which can be tedious. It would be great if items were automatically picked up when the player walks near them, similar to the default behavior in Minecraft.

### Problem and Solution

This feature would solve the issue of having to manually pick up items, which can be time-consuming and disrupt gameplay. Implementing automatic item pickup would make the game experience smoother and more enjoyable, especially when dealing with large quantities of dropped items.

### Alternatives Considered

I have thought about manually binding a key to pick up items, but an automatic feature would be more intuitive and seamless.

### Additional Context

Potential challenges in implementation might include balancing the feature to prevent excessive item collection that could overwhelm the inventory or cause performance issues. It would also be important to consider whether the feature should work only for certain item types or all items.

**Comment by Kuyuna** [comment]
Yes, super annoying. Went mining and didn‘t pick up any stone at all and then my pickaxe broke.

**Comment by TheButterbrotMan** [comment]
Disabled manual pick up setting.
